name = "9router"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[alias]
"@/lib/usageDb.js" = "./src/stubs/usageDb.js"

# Step 3: Paste your KV & D1 IDs here
[[kv_namespaces]]
binding = "KV"
id = "a098a3553ba348b59f32072008e588c4"

[[d1_databases]]
binding = "DB"
database_name = "proxy-db"
database_id = "b6798d5b-c09d-4eee-aa65-541660eae223"
